export const projects = [
  {
    name: "Planets",
    lname: "Planets Facts Site",
    link: "https://www.frontendmentor.io/challenges/planets-fact-site-gazqN8w_f",
    img: "planets.svg",
    routeName: "Planets",
    bgColor: "#070724",
    color: "#fff",
    shadow: "#6D2ED5",
    date: "01/01/22",
  },
  {
    name: "Room",
    lname: "Room Homepage",
    link: "https://www.frontendmentor.io/challenges/room-homepage-BtdBY_ENq",
    img: "room.png",
    routeName: "Room",
    bgColor: "#ffffff",
    color: "#454545",
    shadow: "#ffb53d99",
    date: "03/01/22",
  },
  {
    name: "Countries",
    lname: "REST Countries",
    link: "https://www.frontendmentor.io/challenges/rest-countries-api-with-color-theme-switcher-5cacc469fec04111f7b848ca",
    img: "room.png",
    routeName: "Countries",
    bgColor: "#ffffff",
    color: "#454545",
    shadow: "#ffb53d99",
    date: "01/04/22",
  },
];
